### ISSUE TITLE
Issue with jackson dependency

### ISSUE THREAD

**Issue by rameka** [Celos/avro-json-decoder#5] opened 2020-06-09 00:27 UTC
Currently I am working on a gradle project that on I am using `com.fasterxml.jackson` `org.codehaus.jackson` and for some reason `avro-json-decocder` considers `com.fasterxml.jackson` as it's dependency instead of `org.codehaus.jackson`.  Which is causing a `java.lang.NoClassDefFoundError: org/codehaus/jackson/JsonNode` when running my tests.

I checked the `pom.xml` for this repo and couldn't find any artifactId with either of the jackson packages. How could I resolve this?

**Comment by Celos** [comment] 2020-06-09 06:14
This doesn't have a direct jackson dependency, whatever you see comes from avro itself. You're probably using avro 1.9+ , so this issue would be a duplicate of #3.

**Closed as completed by Celos** 2020-06-09 06:14 UTC
Labels: duplicate
